<h1 align="center"><font color="orange">Assignment <br><br> Numpy</font></h1>

# Theory Question  

<hr style="border:0.3px solid orange; width:100%"></hr>

## Q1. Explain the purpose and advantages of Numpy in scientific computing and data analysis  .How does it enhances Python's capabilities for numerical operations?

<b>Numpy</b> is a general-purpose array-processing package . It provides a high -performance multidimensional array object, and tools for working with these arrays.It is the fundamental package for scientific computing with Python .   
<b> Advantages of Numpy-:</b> 
- <b>performance</b>: Numpy array operation are executing at compiled C  speed ,making  them significantly faster than equialent operations performed using Python lists. The performance boost is vital for handling large datasets and complex compution efficiently.
-  <b>Memory Efficiency </b> : Numpy memory are contiguous memory block , reducing overhead compared to python lists. This memory efficiency is essenttial when dealing with extensive datasets and enables faster data acesss and manipulation .
-  <b>Extensive Mathematical Functions:</b> Numpy provides a rich collection of Mathmatical functions ,making it an indispensable tool for scienctific computing, liner algebra ,statistics and more . These functios streamline complex caluculation and data transformations.
-  <b> Interoperability:</b> Numpy integrates with other liberary and tools in the scientific python ecosystem ,such as Scipy,Pandas ,Matplotlib etc.
This integration allow for  comprehensive data analysis ,visualization, and machine learning .


<b> Use Cases:</b>  
-  <b>Data Analysis and Preprocessing:</b> Nump is widely used in data analysis task,including data cleaning ,manipulation and transformation  , due to its efficient array operation and mathmatical functinalities.
-  <b> Scientific Computing :</b> Application inn physics ,biology,engineering and finance leverage Numpy for sumlations,solving differentials  equations ,numerical integration and more.
-  <b>Machine leanings :</b>  Numpy forms the backbone of many machine learnings algorithms by handling data representtation and mathemaical computations efficiently,supporting task like features extraction ,data normalization and model evaluation.

### How does it enhance python capabilities for numerical operations:    
Numpy is built around the idea of homogenuous data array.Although Numpy array can specify and support various data types ,any array created in Numpy.  should only one desired data types -- a different array can be made for a different data type.  
This approach requires less memory and allow more efficient system performance when processing mathematical operation on array elements.  


In [58]:
# multiplication of two array
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[6,7,8],[8,7,4],[3,4,5]])
print("multiplication of both array:\n",a@b)

multiplication of both array:
 [[31 33 31]
 [65 69 65]]


***

## Q2. Compare and contrast np.mean() and np.average()function in Numpy. When would you use one over the other?

<table>
    <tr>
        <th>np.mean()</th>
        <th>np.average()</th>
    </tr>
    <tr>
        <td>Use to calculate arithmetic mean</td>
        <td>use to calculate the arithmetic mean as well as weighted average</td>
    </tr>
    <tr>
        <td>All elements have equal weight </td>
        <td> All elements may or may not have equal weight</td>
    </tr>
    <tr>
        <td> Weight can not be passed through the parameter of he given function .</td>
        <td>Weight can be passed through the parameter of the given function</td>
    </tr>
    <tr>
        <td>Syntax: np.mean(arr,axis=None)</td>
        <td>Syntax: np.average(arr,axis=None,weights=None)</td>
    </tr>
    <tr>
        <th></th>
        <th></th>
    </tr>
</table>

In [59]:
# Expample np.mean()
import numpy as np
data=np.array([[1,2,3,4,5],[4,5,6,8,4]])
print("mean of data",np.mean(data,axis=1))

mean of data [3.  5.4]


In [60]:
# example np.average
import numpy as np 
data=np.array([[1,2,3,4,5],[4,5,6,8,4]])
weights=np.array([[9,8,7,6,5],[8,3,2,7,6]])
print("average  of data :",np.average(data,axis=1,),"\nweight of data:",np.average(data,axis=1,weights=weights))

average  of data : [3.  5.4] 
weight of data: [2.71428571 5.34615385]


***

## Q3. Describe the methods for reversing a Numpy array along different axes .Provides example for 1D and 2D array?

### using flip() : The numpy.flip() function reverse the order of array elements along the specified axis,preserving the shape of the array.


In [89]:
# 1D arrayy
import numpy as np
arr=np.asarray([1,2,3,4,5,6,7])
print("reverse numpy 1D array:",np.flip(arr))

reverse numpy 1D array: [7 6 5 4 3 2 1]


In [62]:
# 2D array
import numpy as np
arr1= np.asanyarray([[1,2,3,4],[5,6,7,8]])
print("reverse numpy 2D array specified axis :\n",np.flip(arr1,axis=1))
print("reverse numpy 2D array specified axis :\n",np.flip(arr1,axis=0))
print("reverse numpy 2D array :\n",np.flip(arr1))

reverse numpy 2D array specified axis :
 [[4 3 2 1]
 [8 7 6 5]]
reverse numpy 2D array specified axis :
 [[5 6 7 8]
 [1 2 3 4]]
reverse numpy 2D array :
 [[8 7 6 5]
 [4 3 2 1]]


### using list_slicing method : This method makes a copy of the list instead of sorting it in oreder .To accommodate all of the current components  making a clone requires additionl room. More RAM used in this way 

In [63]:
# reverse 1D array
import numpy as np
arr2=np.asarray([7,8,9,5,4])
print("reverse 1D array using list_slicing",arr2[::-1])

reverse 1D array using list_slicing [4 5 9 8 7]


In [64]:
# reverse 2D array
import numpy as np
arr3=np.asarray([[7,8,9,5,4],[4,5,6,7,8]])
print("reverse 2D array using list_slicing\n",arr3[::-1])

reverse 2D array using list_slicing
 [[4 5 6 7 8]
 [7 8 9 5 4]]


### numpy.flipud() : filps the arrays in up-town direction,shape preserved

In [65]:
# 1D array 
import numpy as np
a=np.array([8,9,5,6,7])
print("reverse 1D arrayy using flipud():",np.flipud(a))

reverse 1D arrayy using flipud(): [7 6 5 9 8]


In [66]:
# 2D array 
import numpy as np
a1=np.array([[8,9,5,6,7],[4,5,6,7,9]])
print("original array : \n",a1)
print("reverse 2D arrayy using flipud():\n",np.flipud(a1))

original array : 
 [[8 9 5 6 7]
 [4 5 6 7 9]]
reverse 2D arrayy using flipud():
 [[4 5 6 7 9]
 [8 9 5 6 7]]


***

## Q4. How can you determine the data type of elements in Numpy array? Disucuss the importance of data types in memory management  and performance ?

### Data types of Array : you can check the types of data present in the numpy array using the 'dtype' attribute.   
By default python have these data types:   
- strings- used to represents text data,the text is given unique quote marks.
- integer- used to represents integer numbers.
- float- used to represents real numbers.
- boolean- used to represent True or False
- complex- used to represent complex numbers.


In [67]:
import numpy as np
a=np.array([2,3,4])
b=np.array([2.3,4.5,7.8])
c=np.array(["ram","sita"])
d=np.array([True,False])
e=np.array([3+4j,5+6j])
print("types of a:",a.dtype)
print("types of b:",b.dtype)
print("types of c:",c.dtype)
print("types of d:",d.dtype)
print("types of e:",e.dtype)

types of a: int32
types of b: float64
types of c: <U4
types of d: bool
types of e: complex128


### Disucuss the importance of data types in memory management and performance :-
 A data types is an attribute associated witha piece of data that tells a computer system how to inerpret its value .Understanding data types ensures that data is collectedin the preferred format and value of each property is as expected.

***

## Q5. Define ndarrays in Numpy and explain their key features . How do they differ from standard Python list?

The primary data structure in Numpyy is the N-dimensional array -- called an ndarray or simple an array. Every ndarray is a fixed-size array that is kept in memory and contans the same type of data such as integer or floating-point numbers.  
An ndarray can possess up to three dimensions including array length, width,and height or layers .The data type used in the arrayy is specified through the dtype attribute assigned to the array.    
### Feature of Numpy :  
- Multi-Dimensional : It provides convenient way to create ,manipulate and perform operation on array of arbitary dimensions. This makes it ideal for handling large datasets,imagesand other types of numerical data.
- Broadcasting : It allow Numpy to operate on arrays of different dimensions and shapes without the need for explicit loops.When we perform an operation between two arrays with different shapes , numpy tries to broadcast the arrays to a common shape before performing the operation.
- vectorized Operation : These operation are performed element -wise on array , and they are much faster then using expicit loops.
- Indexing and Slicing : It can be sliced along an axis , and you can use Boolean indexing to select elements that meet certain criteria
- Array-Manipulation : Numpy provides a wide range of functions for manipulating arrays. You can concatenate,stack,split and resahape array and ou can tranpose and flatten array.
- Linear-algebra : It includes a linear algebra ,library that provides function for performing such operation such as matrix multiplication,determinantts and eigenvalues.

### How do they differ from standard Python list?¶

<table>
    <tr>
        <th>Feature </th>
        <th>Arrays</th>
        <th>List</th>
    </tr>
    <tr>
        <td>Homogenity</td>
        <td> All Element must be of the same type</td>
        <td>It can contain elementsof different types</td>
    </tr>
    <tr>
        <td>Size-Flexibility</td>
        <td>Fixed-size once created</td>
        <td>Dynamic size : can grow or shrink as needed</td>
    </tr>
    <tr>
        <td>Memory Efficiency</td>
        <td>More memory efficient due to homogeneity</td>
        <td>Less memory efficient due to the potential type variablity</td>
    </tr>
    <tr>
        <td>Built in methods</td>
        <td>fewer built-in method</td>
        <td>Rich set of built-in methods for various operations </td>
    </tr>
    <tr>
        <td>Data access</td>
        <td>Direct access using index</td>
        <td>Direct access using index</td>
    </tr>
    <tr>
        <td>Type Specification</td>
        <td> Require a type code during creation</td>
        <td>No type specification is needed</td>
    </tr>
    
</table>

In [68]:
import numpy as np
a=np.zeros((1,1,3,4))
print("original n-array:",a)
print("dimension of n-array:",a.ndim)
print("shape of n-array:",a.shape)
print("size of n-arrayy:",a.size)

original n-array: [[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]
dimension of n-array: 4
shape of n-array: (1, 1, 3, 4)
size of n-arrayy: 12


***

## Q6. Analyze the performance denefit of Numpy arrays over Python list for large-scale numerical operations?

### Numpy array :  
- we can create an N-dimensional array in Pyhon using Numpy.array()
- Element- wise operation is possible
- Numpy array has various function ,methods, and variables , to ease our task of matrix computation

  ### Python list:
- The list can be homogenuous or hetterogenuous .
- Element - wise operation is not possible on the list
- Element of a list need not be contiguous in memory
- 
### Performance:   
Numpy arrayy operations are executed at compiled C speed ,making them significantly faster than equivalent operations performed using Pyhon list.
This performance boost is vital for handling large datasets and complex computations efficiently






In [69]:
#Example: Numpy array
import numpy as np
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
print("sum of two array :",np.add(a,b))
print("subraction of two array :",np.subtract(a,b))
print("multiplication of two array :",np.multiply(a,b))




sum of two array : [ 5  7  9 11]
subraction of two array : [-3 -3 -3 -3]
multiplication of two array : [ 4 10 18 28]


***

## Q7. Compare vstack() and hstack() functions in Numpy Provides example demonstrating their usage and output?

### numpy.vstack():   It is a tool in Python liberary that allow you to stack arrays vertically . In simpler terms,it takes a sequence of arrays and stacks them vertically to make a single array.
    Syntax:  numpy.vstack(tup)

In [70]:
#Example: np.vstack()
import numpy as np 
a=np.asarray([89,76,54,34])
b=np.asarray([56,43,2,34])
print("stack arrays vertically:\n",np.vstack((a,b)))

stack arrays vertically:
 [[89 76 54 34]
 [56 43  2 34]]


### numpy.hstack():-  It is used to stack tthe sequence of input arrays horizontally to make a single array.
  Syntax:  numpy.hstack(tup)

In [71]:
#Example: np.hstack()
import numpy as np 
a=np.asarray([89,76,54,34])
b=np.asarray([56,43,2,34])
print("stack arrays vertically:\n",np.hstack((a,b)))

stack arrays vertically:
 [89 76 54 34 56 43  2 34]


***

## Q8. Explain the differences between fliplr() and flipud() method in Numpy ,including their effects on various array dimensons?

### numpy.flipud():   It use to flip ndarray verticle means up and down.
numpy.flipud() return a view . Becauses  view shares memory with the original array,changing one value changes the other  

In [72]:
import numpy as np
a=np.array([56,78,76,45,34])
b=np.array([67,89,45,34,23])
print(np.flipud((a,b)))

[[67 89 45 34 23]
 [56 78 76 45 34]]


### numpy.fliplr(): Itt use ndarray horizonttally means left and right  

In [73]:
import numpy as np
a=np.array([56,78,76,45,34])
b=np.array([67,89,45,34,23])
print(np.fliplr((a,b)))

[[34 45 76 78 56]
 [23 34 45 89 67]]


***

## Q9. Discuss the functionality of the array_split() method in Numpy . How does it handle uneven splits?

Array splitting in NumPy is like a slice of cake . Think of each element in a NumPy array as a slice of cake .Splitting divides this cake into smaller "slices".  
Splitting ia reverse operation of joining .  
joining merge multiple arrays into one and Splitting breaks one array into multiple  
We use array_split() for splitting arrays,we pass it the array we want to split and the number of splits.   

### Axis:  
The dimensions along which the array is split.
### Sub-arrays:  
The smaller arrays resulting from the split.  
### Splitting method :  
Different functions in NumPy for splitting arrays  
### Equal vs Unequal :    
Whether the sub -arrays have the same size or not


In [74]:
import numpy as np
arr=np.asarray([2,3,4,5,6,7])
print("split of single array:",np.array_split(arr,2))

split of single array: [array([2, 3, 4]), array([5, 6, 7])]


***

## Q10. Explain the concepts of vectorization and broadcasting in Numpy. How do they contribute to efficient array operations?

### Vectorization :  
vectorization technique used in Python an arrayys to implement functions an arrays without using for loops. It is implementing using the numpy module and uses pre-defined functions.  These functions are optimized and reduced the calculation time.

In [75]:
import numpy as np
arr1=np.arange(1,30,4)
arr2=np.array([2,4,6,8,10,12,14,16])
def fun(arr1,arr2):
    return arr1+arr2
vectorization=np.vectorize(fun)
print("Sum of the element of arrayy1 and array2 are :\n",vectorization(arr1,arr2))

Sum of the element of arrayy1 and array2 are :
 [ 3  9 15 21 27 33 39 45]


### Broadcasting :  
The term broadcasting refers to the ability of NumPy to treat arrays with different dimensions during arithmetic operation ,This process involves certain rules that allow the similar array to be 'broadcasting ' across the larger one,ensuring that they have compatiable shapes for these operations.

In [76]:
import numpy as np
a=np.ones((3,3),dtype=int)
print("original array :\n",a)
print("after adding 5 into array :\n",a+5)
print("after multiply 24 into array :\n",(a*24))
print("after subtract 5 into array :\n",a-5)

original array :
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
after adding 5 into array :
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
after multiply 24 into array :
 [[24 24 24]
 [24 24 24]
 [24 24 24]]
after subtract 5 into array :
 [[-4 -4 -4]
 [-4 -4 -4]
 [-4 -4 -4]]


***

# Practical Question

## Q1. Create a 3*3 NumPy array with random integers between 1 and 100 .Then, interchange its rows and columns

In [77]:
import numpy as np
arr=np.random.randint(1,100,size=(3,3))
print("array random 3 * 3 with random integers between 1 and 100 :\n",arr)
print("interchange its rows and columns of arr: \n",arr.T)

array random 3 * 3 with random integers between 1 and 100 :
 [[91 36  6]
 [60 95 71]
 [33 77  2]]
interchange its rows and columns of arr: 
 [[91 60 33]
 [36 95 77]
 [ 6 71  2]]


***

## Q2. Generate a 1D  NumPy array  with 10 elements Reshape it into a 2 * 5 array, then into a 5 * 2 array

In [78]:
import numpy as np
arr1=np.array([34,47,51,78,98,34,23,19,340,560])
print("original array : \n",arr1)
print("shape of array of arr1 :\n",arr1.shape)
arr2=arr1.reshape((2,5))
print("array 2 * 5:\n ", arr2)
print("shape of array of arr2 :\n",arr2.shape)
arr3=arr1.reshape((5,2))
print("array 5 * 2:\n ", arr3)
print("shape of array of arr3 :\n",arr3.shape)




original array : 
 [ 34  47  51  78  98  34  23  19 340 560]
shape of array of arr1 :
 (10,)
array 2 * 5:
  [[ 34  47  51  78  98]
 [ 34  23  19 340 560]]
shape of array of arr2 :
 (2, 5)
array 5 * 2:
  [[ 34  47]
 [ 51  78]
 [ 98  34]
 [ 23  19]
 [340 560]]
shape of array of arr3 :
 (5, 2)


## Q3. Create a 4 * 4 NumPy array with random float values .Add a border of zeros arround it, resluiting in a 6 * 6 array

In [79]:
import numpy as np
arr = np.random.random((4,4))
arr2= np.pad(arr,pad_width=1, mode='constant',constant_values=0)
print("Add a border of zeros arround it, resluiting in a 6 * 6 array:\n",arr2)
print("shape of array:",arr2.shape)

Add a border of zeros arround it, resluiting in a 6 * 6 array:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.95906793 0.26374306 0.75988971 0.23916466 0.        ]
 [0.         0.18141066 0.49838017 0.5043104  0.5068496  0.        ]
 [0.         0.66623679 0.1668673  0.08334955 0.62444328 0.        ]
 [0.         0.44007851 0.96466477 0.43411352 0.01702889 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
shape of array: (6, 6)


## Q4. Using NumPy  create an array of integers from 10 to 60 with a step 5.

In [80]:
import numpy as np
arr=np.arange(10,60,5)
print("create an array of integers from 10 to 60 with a step 5 :\n",arr)


create an array of integers from 10 to 60 with a step 5 :
 [10 15 20 25 30 35 40 45 50 55]


## Q5. Create a NumPy array of Strings['python,'numpy','pandas'].Apply different cases transormations (uppercase ,lowercase,title case etc) to each element.

In [81]:
import numpy as np 
arr=np.asarray(['python','numpy','pandas'] ,dtype = str)
print("original array :\n:",arr)
print("uppercase of string in array :",np.char.upper(arr))
print("lowercase of string in array :",np.char.lower(arr))
print("title case of string in array :",np.char.title(arr))
print("capitalise of string in array :",np.char.capitalize(arr))


original array :
: ['python' 'numpy' 'pandas']
uppercase of string in array : ['PYTHON' 'NUMPY' 'PANDAS']
lowercase of string in array : ['python' 'numpy' 'pandas']
title case of string in array : ['Python' 'Numpy' 'Pandas']
capitalise of string in array : ['Python' 'Numpy' 'Pandas']


***

## Q6. Generate a NumPy array of words .Insert a space between each character of every word in tha array.

In [82]:
import numpy as np 
arr= np.asarray(["Ram","Sita","Gita","Mohan","Sohan"],dtype=str)
print("Insert a space between each character of every word in tha array.¶:",np.char.join("  ",arr))

Insert a space between each character of every word in tha array.¶: ['R  a  m' 'S  i  t  a' 'G  i  t  a' 'M  o  h  a  n' 'S  o  h  a  n']


***

## Q7. Create two 2D Numpy array and perform element-wise addition ,subtraction,multiplication and division.

In [83]:
import numpy as np 
arr1=np.random.randint(1,5,size=(2,2))
print("first array:\n",arr1)
arr2=np.random.randint(1,10,size=(2,2))
print("second array:\n",arr2)
print("addition of two array:\n",np.add(arr1,arr2))
print("subtracti onof two array:\n",np.subtract(arr1,arr2))
print("multiplication  of two array:\n",np.dot(arr1,arr2))
print("division of two array:\n",np.divide(arr1,arr2))


first array:
 [[2 4]
 [4 3]]
second array:
 [[1 6]
 [5 9]]
addition of two array:
 [[ 3 10]
 [ 9 12]]
subtracti onof two array:
 [[ 1 -2]
 [-1 -6]]
multiplication  of two array:
 [[22 48]
 [19 51]]
division of two array:
 [[2.         0.66666667]
 [0.8        0.33333333]]


***

## Q8. Use NumPy to create a 5 * 5 identity matrix ,then extract its diagonal elements

In [84]:
import numpy as np
a=np.eye(5,5,dtype=int)
print("identity matrix :\n",a)

identity matrix :
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [85]:
import numpy as np
arr=np.diag([1,1,1,1,1])
print("identity matrix :\n",arr)

identity matrix :
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


***

## Q9. Generate a NumPy array of 100 random integers between 0 to 1000 . Find and display all prime numbers in this array.

In [86]:
def is_prime(n):
    if n==0 or n==1:
        return False
    for i in range(2,n//2+1):
        if n% i== 0:
           return False
    return True
import numpy as np 
a=np.random.randint(0,1000, 100)
foo = np.vectorize(is_prime)
pbools = foo(a)
primes = np.extract(pbools, a)
print("Generate a NumPy array of 100 random integers between 0 to 1000:\n\n ",a)
print("\n")
print("*****************************************************************")
print("display all prime numbers in this array.:\n\n",primes)
       

Generate a NumPy array of 100 random integers between 0 to 1000:

  [583 324 116 637 759 506 266  99 964  10 209 402 389 659   3 289 546 675
 220 606  39 672 923 142  14 280  63 731 246 883  89 909 472 615 625 912
  89 354 584 330 486 830 951  25 351 651 898 912 884 484 346 984 382 841
 731 307 368 442 144 997 339 998 200 493 961 641  82 250 504 191 341 734
 373 744 593 743 183 788 163 726 122 490 561 130 924 208 229 883 747  39
 347 933 127 279 138 147 288 868 166 114]


*****************************************************************
display all prime numbers in this array.:

 [389 659   3 883  89  89 307 997 641 191 373 593 743 163 229 883 347 127]


***

In [87]:
import numpy as np
import math

def is_prime(n):
    if n % 2 == 0 and n > 2: 
        return False
    return all(n % i for i in range(3, int(math.sqrt(n)) + 1, 2))

a = np.random.randint(1, 10**3,100)
pbools =np.array([is_prime(x) for x in a])
primes = np.extract(pbools, a)
print("Generate a NumPy array of 100 random integers between 0 to 1000:\n\n ",a)
print("\n")
print("*****************************************************************")
print("display all prime numbers in this array.:\n\n",primes)


Generate a NumPy array of 100 random integers between 0 to 1000:

  [321 265 277 764 425 427 821 661  18 244 171  70 706 714 596 347 692 343
 609 187  49 910 236 346  52 834 163 433 279 368 591 415 308 378 988 952
 638 629 100 802 847 167 479  85 431 277 728  35 917 728 965  37 901  56
 734  35 744 978 724 391 325 540 392 481 902 187 625 498 427 199 528 720
 106 516 704 196 590  58 333 842 967 182 356 923 906 131 376 804 257 511
 796 470 213 588 926 848 678 342 101  68]


*****************************************************************
display all prime numbers in this array.:

 [277 821 661 347 163 433 167 479 431 277  37 199 967 131 257 101]


***

## Q10. Create a NumPy array representing daily temperatures for a month . Calculate and display the weekly averages.

In [88]:
import numpy as np
import pandas as pd
temperature=np.random.uniform(25,100,28)
temp_weekly=temperature.reshape(4,7)
print("daily temperature of month:\n\n",temperature)
print("---------------------------------------------------")
print("weekly temperature in month :\n\n",temp_weekly)
print("---------------------------------------------------")
print("display the weekly averages :",temp_weekly.mean())




daily temperature of month:

 [43.32464061 64.03899751 87.21335925 52.3044887  60.55893557 93.71970357
 25.54702843 63.54859243 27.21276115 30.88222373 25.71385496 27.51188372
 64.65710653 90.46744743 78.55078909 56.88767813 69.79910734 96.76831858
 78.78702751 62.68943521 53.84466876 89.87050096 96.48963701 77.12143491
 93.90523342 77.14786877 58.46079921 71.90522158]
---------------------------------------------------
weekly temperature in month :

 [[43.32464061 64.03899751 87.21335925 52.3044887  60.55893557 93.71970357
  25.54702843]
 [63.54859243 27.21276115 30.88222373 25.71385496 27.51188372 64.65710653
  90.46744743]
 [78.55078909 56.88767813 69.79910734 96.76831858 78.78702751 62.68943521
  53.84466876]
 [89.87050096 96.48963701 77.12143491 93.90523342 77.14786877 58.46079921
  71.90522158]]
---------------------------------------------------
display the weekly averages : 64.96174085979555


***